---

- name: requirements > Golang check
  command: "go --version"
  always_run: yes
  failed_when: false
  changed_when: false
  register: _elao_go_check_output

- name: requirements > Golang check fail
  fail:
    msg: Need golang, you can use https://github.com/ElaoInfra/ansible-role-apt to install it.
  when: _elao_go_check_output.stdout is not defined
